server:
  port: 8888
spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: productServiceRoute
          predicates:
            - Path=/products/**
          uri:  lb://product-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false